---
title: "Create Plots"
author: "Christopher Prener, Ph.D."
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: 
  github_document: default
  html_notebook: default 
---

## Introduction
This notebook creates plots of homicide rates, violent crime rates, and larceny rates.

## Dependencies
This notebook requires a number of plotting packages:

```{r load-packages}
# tidyverse packages
library(dplyr)
library(ggplot2)
library(readr)

# other packages
library(ggthemes)
library(here)
```

## Load Data
This notebook requires the previously created crime trends data:

```{r load-data, echo=FALSE, message=FALSE}
stLouis <- read_csv(here("data", "clean", "STL_CRIME_Trends.csv"))
```

## Plots

### Homicide Count

```{r homicide-count}
plot <- stLouis %>%
  ggplot(aes(x = year, y = murder)) +
    geom_line(color = "#ff0000", size = 1.5) + 
    scale_y_continuous(breaks = c(seq(0, 350, by = 50)), limits = c(0, 350)) +
    scale_x_continuous(breaks = c(1946, seq(1950, 2015, by = 5), 2021)) +
    labs(title = "Homicide Trend for St. Louis City, 1946-2021", 
         subtitle = "Count of Homicides",
         caption = "Plot by Christopher Prener, Ph.D.\nData via the FBI and the St. Louis Post-Dispatch") +
  theme_fivethirtyeight()

ggsave(here("results", "homicide_count.png"), plot,
       width = 6.5, height = 4.75, units = "in")

plot
```

### Homicide Rate

```{r homicide-rate}
plot <- stLouis %>%
  ggplot(aes(x = year, y = murderRate)) +
    geom_line(color = "#ff0000", size = 1.5) + 
    scale_y_continuous(breaks = c(seq(0, 90, by = 15)), limits = c(0, 90)) +
    scale_x_continuous(breaks = c(1946, seq(1950, 2015, by = 5), 2021)) +
    labs(title = "Homicide Trend for St. Louis City, 1946-2021", 
         subtitle = "Rate per 100,000 Residents",
         caption = "Plot by Christopher Prener, Ph.D.\nData via the FBI and the St. Louis Post-Dispatch") +
  theme_fivethirtyeight()

ggsave(here("results", "homicide_rate.png"), plot,
       width = 6.5, height = 4.75, units = "in")

plot
```

### Aggravated Assault Rate

```{r ag-rate}
plot <- stLouis %>%
  ggplot(aes(x = year, y = agAssaultRate)) +
    geom_line(color = "#663399", size = 1.5) + 
    scale_y_continuous(breaks = seq(0, 2250, by = 250), limits = c(0, 2250)) +
    scale_x_continuous(breaks = c(1946, seq(1950, 2015, by = 5), 2021)) +
    labs(title = "Aggravated Assault Trend for St. Louis City, 1946-2021", 
         subtitle = "Rate per 100,000 Residents",
         caption = "Plot by Christopher Prener, Ph.D.\nData via the FBI and the St. Louis Post-Dispatch") +
    theme_fivethirtyeight()

ggsave(here("results", "agg_assault_rate.png"), plot,
       width = 6.5, height = 4.75, units = "in")

plot
```

### Violent Crime Rate

```{r violent-rate}
plot <- stLouis %>%
  filter(year >= 1958) %>%
  ggplot(aes(x = year, y = violentRate)) +
    geom_line(color = "#0000ff", size = 1.5) + 
    scale_y_continuous(breaks = seq(0, 4000, by = 500), limits = c(0, 4000)) +
    scale_x_continuous(breaks = c(1958, seq(1965, 2015, by = 5), 2021)) +
    labs(title = "Violent Crime Trend for St. Louis City, 1958-2021", 
         subtitle = "Rate per 100,000 Residents",
         caption = "Plot by Christopher Prener, Ph.D.\nData via the FBI and the St. Louis Post-Dispatch \nViolent crimes include homicide, rape, robbery, and aggravated assault.") +
    theme_fivethirtyeight()

ggsave(here("results", "violent_rate.png"), plot,
       width = 6.5, height = 4.75, units = "in")

plot
```

### Larceny Rate

```{r larceny-rate}
plot <- stLouis %>%
  filter(year >= 1949) %>%
  ggplot(aes(x = year, y = theftRate)) +
    geom_line(color = "#00b300", size = 1.5) + 
    scale_y_continuous(breaks = seq(0, 14000, by = 2000), limits = c(0, 14000)) +
    scale_x_continuous(breaks = c(1949, seq(1955, 2015, by = 5), 2021)) +
    labs(title = "Larceny Trend for St. Louis, 1949-2021", 
         subtitle = "Rate per 100,000 Residents",
         caption = "Plot by Christopher Prener, Ph.D.\nData via the FBI \nLarcenies include burglary, larcency, and larceny of a motor vehicle.") +
    theme_fivethirtyeight()

ggsave(here("results", "larcency_rate.png"), plot,
       width = 6.5, height = 4.75, units = "in")

plot
```

